---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-emptydir-volume
spec:
  containers:
    - image: alpine
      name: alpine-container
      args:
       - /bin/sh
       - -c
       - sleep 1d
      volumeMounts:
        - mountPath: /var/log
          name: testconfigmap

  volumes:
    - name: testconfigmap
      secret:
        secretName : mysecret
    