---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-server
  labels:
     app: mysqldb
spec:
  selector:
    matchLabels:
      app: mysqldb
      tier: db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysqldb
        tier: db
    spec:
      containers:
        - image: mysql:5.6
          name: mysql
          env:
           - name: MYSQL_ROOT_PASSWORD
             valueFrom:
               secretKeyRef:
                 name:mysql-pass
                 key:password<
          ports:
            - containerPort: 3306
                name: mysql
          volumeMounts:
            - name: mysql-pv
              mountPath: /var/lib/mysql
    volumes:
      - name: mysql-pv
        persistentVolumeClaim:
          claimName: mysql-pvc

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: mysql-sc