---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx
spec:
  minReadySeconds: 1
  serviceName: nginx-svc
  replicas: 3
  selector:
    matchLabels:
      app: 'nginx'
  template:
    metadata:
      name: nginx
      labels:
        app: 'nginx'
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - name: htmlhome
              mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
    - metadata:
        name: htmlhome
      spec:
        accessModes: 
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
        storageClassName: managed

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc
spec:
  selector:
    app: nginx
  type: ClusterIP
  clusterIP: None
  ports:
    - name: nginx-svc
      port: 80
      targetPort: 80
      protocol: TCP