---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nginx-rs
  labels:
    app: nginx
spec:
  minReadySeconds: 3
  replicas: 4
  selector:
    matchExpressions:
      - key: app
        operator: In
        values:
          - nginx
          - webserver
      - key: ver
        operator: Exists
  template:
    metadata:
      name: nginx-pod
      labels:
        app: nginx
        ver: "1.23"
    spec:
      containers:
        - name: nginx
          image: nginx:1.23
          ports:
            - containerPort: 80
              protocol: TCP

---
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cicd
  labels:
    app: jenkins
    purpose: cicd
spec:
  replicas: 4
  selector:
    matchLabels:
      purpose: cicd
  template:
    metadata:
      labels:
        purpose: cicd
    spec:
      containers:
       - name: cicd
         image: jenkins/jenkins:lts-jdk11
         ports:
           - containerPort: 8080
             protocol: TCP
      initContainers:
       - name: ping
         image: alpine:3.17.0      
         command: ["ping" ,"-c","4","google.com"]